title: Sylwia Kmiec
# sylwiakmiec.github.io
logo: 
              
description: >
  Data Analyst|Data Scientist <br>
  Graduate of Higher Diploma in Science in Data Analytics for Business - <b> 1st Class Hons Award </b>
  <br><br>
  CCT College Dublin
  <br><br>

            
  <a href="https://www.linkedin.com/in/sylwia-kmiec-39985557/"> View My LinkedIn Profile</a>


theme: jekyll-theme-minimal
