
title: Sylwia Kmiec
# sylwiakmiec.github.io
logo: 
email       : sylwiakmiec@live.ie
              
description: >
  Data Analyst | Data Scientist <br>
  (Python, SQL, Tableau, Excel) 
  <br><br>
  Graduate of <b> Higher Diploma in Science in Data Analytics for Business </b> <br> with 1st Class Hons Award
  <br><br>
  
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="large" data-theme="light" 
  data-type="HORIZONTAL" data-vanity="sylwia-kmiec-39985557" data-version="v1"><a class="badge-base__link LI-simple-link" 
  href="https://ie.linkedin.com/in/sylwia-kmiec-39985557?trk=profile-badge"></a></div>
              
              
  
  
  <br><br>            









theme: jekyll-theme-minimal
