title: Sylwia Kmiec
# sylwiakmiec.github.io
logo: 
description: >
  Student of Higher Diploma in Science in Data Analytics for Business
  <br><br>
  CCT College Dublin
  <br><br>


  <a href="https://www.linkedin.com/in/sylwia-kmiec-39985557/"> View My LinkedIn Profile</a>


theme: jekyll-theme-minimal
