title: Sylwia Kmiec
# sylwiakmiec.github.io
logo: 
              
description: >
  Data Analyst|Data Scientist <br>
  Graduate of <b> Higher Diploma in Science in Data Analytics for Business </b> <br> with 1st Class Hons Award
  <br><br>
  
  

            
  <a href="https://www.linkedin.com/in/sylwia-kmiec-39985557/"> View My LinkedIn Profile</a>


theme: jekyll-theme-minimal
