title: Sylwia Kmiec
# sylwiakmiec.github.io
logo: 
              
description: >
  Data Analyst|Data Scientist <br>
  Graduate of <b> Higher Diploma in Science in Data Analytics for Business </b> <br> with 1st Class Hons Award
  <br><br>
  
  

  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>  
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="sylwia-kmiec-39985557" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://ie.linkedin.com/in/sylwia-kmiec-39985557?trk=profile-badge">Sylwia Kmiec</a></div>
              
  <a href="https://www.linkedin.com/in/sylwia-kmiec-39985557/"> View My LinkedIn Profile</a>


theme: jekyll-theme-minimal
