title: Sylwia Kmiec
<br><br>
# sylwiakmiec.github.io
logo: 
email       : sylwiakmiec@live.ie
              
description: >
  Data Analyst | Data Scientist <br>
  (Python, SQL, Tableau, Excel) 
  <br><br>
  Graduate of <b> Higher Diploma in Science in Data Analytics for Business </b> <br> with 1st Class Hons Award
  <br><br>
  
  
 
linkedin_badge: |
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
              
              
  
  








theme: jekyll-theme-minimal
