title: Sylwia Kmiec
<br><br>
# sylwiakmiec.github.io
logo: 
email       : sylwiakmiec@live.ie
              
description: >
  Data Analyst | Data Scientist <br>
  (Python, SQL, Tableau, Excel) 
  <br><br>
  Graduate of <b> Higher Diploma in Science in Data Analytics for Business </b> <br> with 1st Class Hons Award
  <br><br>
  
  
<a href="https://www.linkedin.com/in/sylwia-kmiec-39985557/"> View My LinkedIn Profile</a>
  
  
              
              
  
  








theme: jekyll-theme-minimal
