title: Sylwia Kmiec
# sylwiakmiec.github.io
logo: 
description: >
  Graduate of <b>Higher Diploma in Data Science in Business</b> <br>
  with 1st Class Hons Award.
  Student at ATU Donegal: Postgraduate Diploma <br><br>
  in Big Data Analytics and Artificial Intelligence
  <br><br>
  

  <a href="https://www.linkedin.com/in/sylwia-kmiec-39985557/"> View My LinkedIn Profile</a>


theme: jekyll-theme-minimal
